### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by irl** [Zebradil/powerline-taskwarrior#1]
Hi,

Thanks for your work on this.

I'd like to package this in Debian. (Debian bug is [#836949](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836949)).

Please tag a release that you consider to be "stable" for me to base the package on.

Thanks,

**Comment by Zebradil** [comment]
Done.

**Comment by Zebradil** [comment]
I mean tag 0.1 was created
