### ISSUE TITLE
Customized colors

### ISSUE THREAD

**Issue by FrankGruellich** [Zebradil/powerline-taskwarrior#4]
Hi,

right now powerline-taskwarrior hardcodes the rather standard highlight groups `information:regular`, `critical:failure`, and `critical:success` and thus does not really allow individual customization for colors.  I think powerline-taskwarrior should use it's own highlight groups.  Users can set them to the now hardcoded defaults, if they want.

Kind regards,
 Frank.

**Comment by Zebradil** [comment]
Package updated (powerline-taskwarrior-0.5). Thanks!
