### ISSUE TITLE
Python 2 issues

### ISSUE THREAD

**Issue by irl** [Zebradil/powerline-taskwarrior#6]
The super() calls don't work, and when buidling the description of the task with the ellipses, that needs to be u"blah" not just "blah".

See: https://anonscm.debian.org/git/pkg-tasktools/powerline-taskwarrior.git/tree/debian/patches/fix_python_2.patch

**Comment by Zebradil** [comment]
Yes, it's not compatible with Python2. However, it would be better to make it compatible. I'll look what I could do.

**Comment by Zebradil** [comment]
And thanks for report!

**Comment by irl** [comment]
The main reason for this being needed is that in Debian, things seem to be Python 2 by default (except Vim).

We want to drop Python 2, but until we can achieve that things must be compatible.

It is for you to decide whether this is something I'll maintain via patches in Debian or if you want to have your repo compatible with both. I don't want to force Python 2 compatibility on you.

**Comment by Zebradil** [comment]
Python 2 is spread enough to have two versions of this tiny plugin. It's not a problem to make it compatible.

**Comment by Zebradil** [comment]
Done with 8881fe5
