### ISSUE TITLE
no context shown after installation

### ISSUE THREAD

**Issue by felixschurk** [Zebradil/powerline-taskwarrior#8]
Hei,
I installed powerline-taskwarrior with pip. Bevor I installed powerline-status and copied the config files to my privat folder like ~/.config/powerline as said in the instruction.
But after adding the function call to ~/.config/powerline/themes/shell/default.json none of the functions work.
powerline-lint does not give any error when parsing.
Attachted ther is a screenshot of setting, context in taskwarrior, and the pip list output.

So I don't quite understand if I did something wrong while installing, or maybe the script is broken.
![Screenshot from 2021-07-30 17-51-36](https://user-images.githubusercontent.com/75752337/127678987-42b3aaff-0fd2-4385-99c1-7146b67c5654.png)

**Comment by felixschurk** [comment]
When I add .next_task or .active_task function, powerline-lint gives me an error like this:

`powerline-lint 

Path /home/felix/.config/powerline/colorschemes/.default.json.swp is not a directory or configuration file

Error while checking theme (key /segments/right/list item 4/function)
found highlight groups list (taskwarrior:next_id) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/home/felix/.config/powerline/themes/shell/default.json", line 46, column 40:
     ... nction": "powerline_taskwarrior.next_task",
                                         ^

Error while checking theme (key /segments/right/list item 4/function)
found highlight group taskwarrior:next_id not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 4/function)
found highlight groups list (taskwarrior:next_desc) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/home/felix/.config/powerline/themes/shell/default.json", line 46, column 40:
     ... nction": "powerline_taskwarrior.next_task",
                                         ^

Error while checking theme (key /segments/right/list item 4/function)
found highlight group taskwarrior:next_desc not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 5/function)
found highlight groups list (taskwarrior:active_id) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/home/felix/.config/powerline/themes/shell/default.json", line 50, column 40:
     ... nction": "powerline_taskwarrior.active_task",
                                         ^

Error while checking theme (key /segments/right/list item 5/function)
found highlight group taskwarrior:active_id not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 5/function)
found highlight groups list (taskwarrior:active_desc) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/home/felix/.config/powerline/themes/shell/default.json", line 50, column 40:
     ... nction": "powerline_taskwarrior.active_task",
                                         ^

Error while checking theme (key /segments/right/list item 5/function)
found highlight group taskwarrior:active_desc not defined in the following colorschemes: solarized
`

**Comment by Zebradil** [comment]
Hi @felixschurk, thanks for reporting.

I'll take a look later today.

Could you also attach `default.json`? You can use triple backticks to make a multiline code block.

Which version of Powerline do you use? How do you run it (what's in `.bashrc`)?

**Comment by Zebradil** [comment]
I did some tests. You *must* add the colorscheme definition into your `.config/powerline/colorschemes/default.json`:
```json
{
  "taskwarrior:context":       "information:regular",
  "taskwarrior:active_id":     { "bg": "mediumgreen", "fg": "black", "attrs": [] },
  "taskwarrior:active_desc":   { "bg": "green", "fg": "black", "attrs": [] },
  "taskwarrior:next_id":       { "bg": "brightyellow", "fg": "black", "attrs": [] },
  "taskwarrior:next_desc":     { "bg": "yellow", "fg": "black", "attrs": [] }
}
```

Otherwise it doesn't work. It is not clear form the README.md, I will update it.

**Comment by Zebradil** [comment]
The readme is updated. I hope it's more clear now.

**Comment by felixschurk** [comment]
Hei @Zebradil,
thank you for the reply.
my .config/powerline/themes/shell/default.json looks like that.
```{
	"segments": {
		"left": [
			{
				"function": "powerline.segments.shell.mode"
			},
			{
				"function": "powerline.segments.common.net.hostname",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.env.user",
				"priority": 30
			},
			{
				"function": "powerline.segments.common.env.virtualenv",
				"priority": 50
			},
			{
				"function": "powerline.segments.shell.cwd",
				"priority": 10
			},
			{
				"function": "powerline.segments.shell.jobnum",
				"priority": 20
			}
		],
		"right": [
			{
				"function": "powerline.segments.shell.last_pipe_status",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.vcs.stash",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.vcs.branch",
				"priority": 40
			},
			{
				"function": "powerline_taskwarrior.context",
				"priority": 70
			},
			{
				"function": "powerline_taskwarrior.next_task",
				"priority": 70
			},
			{
				"function": "powerline_taskwarrior.active_task",
				"priority": 70
			}
		]
	}
}
```

The colorschemes/default.json like that
```
{
	"name": "Default",
	"groups": {
		"information:additional":     { "fg": "gray9", "bg": "gray4", "attrs": [] },
		"information:regular":        { "fg": "gray10", "bg": "gray4", "attrs": ["bold"] },
		"information:highlighted":    { "fg": "white", "bg": "gray4", "attrs": [] },
		"information:priority":       { "fg": "brightyellow", "bg": "mediumorange", "attrs": [] },
		"warning:regular":            { "fg": "white", "bg": "brightred", "attrs": ["bold"] },
		"critical:failure":           { "fg": "white", "bg": "darkestred", "attrs": [] },
		"critical:success":           { "fg": "white", "bg": "darkestgreen", "attrs": [] },
		"background":                 { "fg": "white", "bg": "gray0", "attrs": [] },
		"background:divider":         { "fg": "gray5", "bg": "gray0", "attrs": [] },
		"session":                    { "fg": "black", "bg": "gray10", "attrs": ["bold"] },
		"date":                       { "fg": "gray8", "bg": "gray2", "attrs": [] },
		"time":                       { "fg": "gray10", "bg": "gray2", "attrs": ["bold"] },
		"time:divider":               { "fg": "gray5", "bg": "gray2", "attrs": [] },
		"email_alert":                "warning:regular",
		"email_alert_gradient":       { "fg": "white", "bg": "yellow_orange_red", "attrs": ["bold"] },
		"hostname":                   { "fg": "black", "bg": "gray10", "attrs": ["bold"] },
		"weather":                    { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"weather_temp_gradient":      { "fg": "blue_red", "bg": "gray0", "attrs": [] },
		"weather_condition_hot":      { "fg": "khaki1", "bg": "gray0", "attrs": [] },
		"weather_condition_snowy":    { "fg": "skyblue1", "bg": "gray0", "attrs": [] },
		"weather_condition_rainy":    { "fg": "skyblue1", "bg": "gray0", "attrs": [] },
		"uptime":                     { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"external_ip":                { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"internal_ip":                { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"network_load":               { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"network_load_gradient":      { "fg": "green_yellow_orange_red", "bg": "gray0", "attrs": [] },
		"network_load_sent_gradient": "network_load_gradient",
		"network_load_recv_gradient": "network_load_gradient",
		"network_load:divider":       "background:divider",
		"system_load":                { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"system_load_gradient":       { "fg": "green_yellow_orange_red", "bg": "gray0", "attrs": [] },
		"environment":                { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"cpu_load_percent":           { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"cpu_load_percent_gradient":  { "fg": "green_yellow_orange_red", "bg": "gray0", "attrs": [] },
		"battery":                    { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"battery_gradient":           { "fg": "white_red", "bg": "gray0", "attrs": [] },
		"battery_full":               { "fg": "red", "bg": "gray0", "attrs": [] },
		"battery_empty":              { "fg": "white", "bg": "gray0", "attrs": [] },
		"player":                     { "fg": "gray10", "bg": "black", "attrs": [] },
		"user":                       { "fg": "white", "bg": "darkblue", "attrs": ["bold"] },
		"branch":                     { "fg": "gray9", "bg": "gray2", "attrs": [] },
		"branch_dirty":               { "fg": "brightyellow", "bg": "gray2", "attrs": [] },
		"branch_clean":               { "fg": "gray9", "bg": "gray2", "attrs": [] },
		"branch:divider":             { "fg": "gray7", "bg": "gray2", "attrs": [] },
		"stash":                      "branch_dirty",
		"stash:divider":              "branch:divider",
		"cwd":                        "information:additional",
		"cwd:current_folder":         "information:regular",
		"cwd:divider":                { "fg": "gray7", "bg": "gray4", "attrs": [] },
		"virtualenv":                 { "fg": "white", "bg": "darkcyan", "attrs": [] },
		"attached_clients":           { "fg": "gray8", "bg": "gray0", "attrs": [] },
		"taskwarrior:context":       "information:regular",
  		"taskwarrior:active_id":     { "bg": "mediumgreen", "fg": "black", "attrs": [] },
  		"taskwarrior:active_desc":   { "bg": "green", "fg": "black", "attrs": [] },
  		"taskwarrior:next_id":       { "bg": "brightyellow", "fg": "black", "attrs": [] },
  		"taskwarrior:next_desc":     { "bg": "yellow", "fg": "black", "attrs": [] }
	}
}
```

My powerline call in .bashrc looks like that.
```# Powerline configuration
if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  source /usr/share/powerline/bindings/bash/powerline.sh
fi
```

Powerline is Version 2.7 in /usr/lib/python3/dist-packages so it should be the latest version.

I don't know where I missed a setting. I'm very sorry.

**Comment by Zebradil** [comment]
Did you try restarting `powerline-daemon` (with `powerline-daemon --replace`)?

Did you change any other configuration files? [Main configuration](https://powerline.readthedocs.io/en/master/configuration/reference.html#main-configuration) for example.

I'm a bit puzzled by the `solarized` theme mention in the output of `powerline-lint` which you posted earlier.

**Comment by felixschurk** [comment]
I don't understand it why its pointing to `solarized` theme, as soon as I add `powerline_taskwarrior.next_task`.
In my config.json, the shell colorscheme is set to default.

``` 
"shell": {
                        "colorscheme": "default",
                        "theme": "default",
                        "local_themes": {
                                "continuation": "continuation",
                                "select": "select"
                        }
```
So it should not look onto the solarized colorscheme.

**Comment by Zebradil** [comment]
Let's try to debug this in the following way.
You can create a new python virtual environment, install powerline and powerline-taskwarrior there, activate it, and see if the issue repeats.

```
mkdir /tmp/pw-tw-test
cd /tmp/pw-tw-test
python -m venv .venv
. .venv/bin/activate
which python
# should print: /tmp/pw-tw-test/.venv/bin/python
pip install powerline_status powerline-taskwarrior
# start clean shell
bash --norc
# stop the daemon to not interfere
powerline-daemon --kill
# now enable powerline
. .venv/lib/python3.9/site-packages/powerline/bindings/bash/powerline.sh
```

Let's try this.

**Comment by felixschurk** [comment]
Okay I created the venv.
I put the `powerline_taskwarrior.context` into the new `.venv/lib/python3.9/site-packages/powerline/config_files/themes/shell/default.json` and added `  "taskwarrior:context":        "information:regular" ` to `.venv/lib/python3.9/site-packages/powerline/config_files/colorschemes/default.json`.

After  again killing the powerlien-daemon and restarting powerline, I still can't see the context on the right side of the shell.

**Comment by Zebradil** [comment]
No, you don't need to change powerline configuration. It should take the configuration you have currently in `~/.config/powerline`. The idea is to have a clean powerline installation with your custom user configuration.

But maybe you can try to use my configuration to pinpoint the issue. You can take it from here: https://github.com/Zebradil/dotfiles/tree/master/powerline. Just put the `powerline` directory into `~/.config`. Though, you will have to either install `powerline-gitstatus` or remove it`s segments from the config file.

**Comment by felixschurk** [comment]
Okay, with your configuration its all working, I can finally see the context, active task and all. 
It fixed my issue, but I still don't understand why it didn't worked bevor. 

Thank you a lot.

**Comment by Zebradil** [comment]
It's good to hear! Yet we can do better, if you like ;-)

I'm still not sure how you configure powerline. 
Did you do any changes to the global configuration (that would require using `sudo`)? If so, I would suggest you to revert default configuration and use only user configuration in `~/.config`.
Do you use configuration in `~/.config`? If so, what is the difference with mine configuration? Can you archive the whole `~/.config/powerline` and attach it here? So I can look at it and maybe figure out what's wrong.

**Comment by felixschurk** [comment]
Yes, of course I would like to know what causes the problem.
I did the installation accourding to [https://www.ricalo.com/blog/install-powerline-ubuntu/#configure-tmux](url) and copied in the beginnen the hole config_files out, right now there is only the colorschemes, and themes folder, because I don't need the others.
Attached there are the files theye are stored in ~/.config/
[powerline.tar.gz](https://github.com/Zebradil/powerline-taskwarrior/files/6917574/powerline.tar.gz)

**Comment by felixschurk** [comment]
I found the problem :)

You added an `"above": [{ ..... }]`over the segments blocks left and right. When I added that to my configuration, the tasks shows up.

**Comment by Zebradil** [comment]
That's strange, I thought it doesn't matter where you put a segment (if there is enough space to display that segment according to its priority).

Anyway, I'm happy you solved you issue. I'm going to close this now. Reopen it if you still have issues on this topic.
