### ISSUE TITLE
Count the number of tasks

### ISSUE THREAD

**Issue by CaptainQuirk** [Zebradil/powerline-taskwarrior#9]
Hi,

I'm usually Taskwarrior to store some small things I have to do, like, looking for some information, sending an email, while development related tasks are usually stored on a tool like Jira or Redmine.
I was wondering if a segment counting the number of pending tasks could be implemented ?

Thanks in advance !

**Comment by Zebradil** [comment]
Implemented in powerline-taskwarrior 1.0.1. Shows a number in square brackets (for ex. `[7]`).

Segment configuration:
```json
{
    "function": "powerline_taskwarrior.pending_tasks_count",
    "priority": 70
}
```

Colorscheme:
```diff
{
  "groups": {
    "taskwarrior:context": "information:regular",
+   "taskwarrior:pending_tasks_count": "information:priority",
    "taskwarrior:active_id": { "bg": "mediumgreen", "fg": "black", "attrs": [] },
    "taskwarrior:active_desc": { "bg": "green", "fg": "black", "attrs": [] },
    "taskwarrior:next_id": { "bg": "brightyellow", "fg": "black", "attrs": [] },
    "taskwarrior:next_desc": { "bg": "yellow", "fg": "black", "attrs": [] }
  }
}
```
